<a href="https://colab.research.google.com/github/Minhyuk03/KMOU_2-2_ML/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5_8%EC%A3%BC%EC%B0%A8_7%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LAB 7-1 AND/OR 연산을 수행하는 퍼셉트론

In [ ]:
def activation_function(x):
    return 1 if x > 0 else -1

def perceptron(x1, x2, w1, w2, b):
    weighted_sum = x1 * w1 + x2 * w2 + b
    return activation_function(weighted_sum)

# AND 연산을 위한 퍼셉트론
# 적절한 가중치(w1, w2)와 편향(b)을 설정
w1_and, w2_and, b_and = 0.5, 0.5, -0.7
print("LAB 7-1\n")
print("AND 연산 결과:")
print(f"입력 ( 1,  1): {perceptron(1, 1, w1_and, w2_and, b_and)}")
print(f"입력 ( 1, -1): {perceptron(1, -1, w1_and, w2_and, b_and)}")
print(f"입력 (-1,  1): {perceptron(-1, 1, w1_and, w2_and, b_and)}")
print(f"입력 (-1, -1): {perceptron(-1, -1, w1_and, w2_and, b_and)}")

# OR 연산을 위한 퍼셉트론
# 적절한 가중치(w1, w2)와 편향(b)을 설정
w1_or, w2_or, b_or = 0.5, 0.5, 0.2

print("\nOR 연산 결과:")
print(f"입력 ( 1,  1): {perceptron(1, 1, w1_or, w2_or, b_or)}")
print(f"입력 ( 1, -1): {perceptron(1, -1, w1_or, w2_or, b_or)}")
print(f"입력 (-1,  1): {perceptron(-1, 1, w1_or, w2_or, b_or)}")
print(f"입력 (-1, -1): {perceptron(-1, -1, w1_or, w2_or, b_or)}")

LAB 7-1

AND 연산 결과:
입력 ( 1,  1): 1
입력 ( 1, -1): -1
입력 (-1,  1): -1
입력 (-1, -1): -1

OR 연산 결과:
입력 ( 1,  1): 1
입력 ( 1, -1): 1
입력 (-1,  1): 1
입력 (-1, -1): -1


LAB 7-2

In [ ]:
import numpy as np
print("LAB 7-2\n")
# XOR 데이터셋 정의
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([0, 1, 1, 0])


# 가중치와 편향 초기화
W = np.zeros(X.shape[1]) # 입력 특성의 수만큼 가중치 초기화
b = 0

# 학습률 (learning rate)
lr = 0.1

# 학습 횟수 (epochs)
epochs = 100

# 퍼셉트론 학습
for epoch in range(epochs):
    for xi, target in zip(X, y):
        linear_output = np.dot(W, xi) + b
        predicted_output = 1 if linear_output >= 0 else -1

        # 오차 계산
        error = target - predicted_output

        # 가중치와 편향 업데이트
        if error != 0:
            update = lr * target

            W += update * xi
            b += update

print("학습된 W:", W)
print("학습된 b:", b)

# 학습된 퍼셉트론으로 예측
print("\n학습된 퍼셉트론으로 예측:")
for xi, target in zip(X, y):
     linear_output = np.dot(W, xi) + b
     y_pred = 1 if linear_output >= 0 else -1
     print(f"입력: {xi}, 실제 타겟: {target}, 예측 결과: {y_pred}")

LAB 7-2

학습된 W: [0. 0.]
학습된 b: 0.0

학습된 퍼셉트론으로 예측:
입력: [0 0], 실제 타겟: 0, 예측 결과: 1
입력: [0 1], 실제 타겟: 1, 예측 결과: 1
입력: [1 0], 실제 타겟: 1, 예측 결과: 1
입력: [1 1], 실제 타겟: 0, 예측 결과: 1


LAB 7-3

In [ ]:
import numpy as np
print("LAB 7-3\n")
def activation_function(x):
    return 1 if x > 0 else -1

def train_perceptron(X, y, learning_rate=0.1, epochs=100):
    # 가중치와 편향 초기화
    W = np.zeros(X.shape[1])
    b = 0

    for epoch in range(epochs):
        for xi, target in zip(X, y):
            # 선형 결합 계산: W * x + b
            linear_output = np.dot(W, xi) + b
            # 예측 결과 (활성화 함수 적용)
            predicted_output = activation_function(linear_output)
            # 오차 계산
            error = target - predicted_output
            # 가중치와 편향 업데이트
            if error != 0:
                update = learning_rate * target

                W += update * xi
                b += update

    return W, b

def predict_perceptron(X, W, b):
    predictions = []
    for xi in X:
        linear_output = np.dot(W, xi) + b
        predictions.append(activation_function(linear_output))
    return np.array(predictions)


# OR 연산 학습 예시
print("OR 연산 학습")
X_or = np.array([[1, 1],
                 [1, -1],
                 [-1, 1],
                 [-1, -1]])
y_or = np.array([1, 1, 1, -1])

W_or, b_or = train_perceptron(X_or, y_or)

print("\n학습된 OR 퍼셉트론으로 예측:")
predictions_or = predict_perceptron(X_or, W_or, b_or)
print(f"입력:\n{X_or}")
print(f"예측 결과: {predictions_or}")
print(f"실제 타겟:   {y_or}")

# AND 연산 학습 예시
print("\nAND 연산 학습")
X_and = np.array([[1, 1],
                  [1, -1],
                  [-1, 1],
                  [-1, -1]])
y_and = np.array([1, -1, -1, -1])

W_and, b_and = train_perceptron(X_and, y_and)

print("\n학습된 AND 퍼셉트론으로 예측:")
predictions_and = predict_perceptron(X_and, W_and, b_and)
print(f"입력:\n{X_and}")
print(f"예측 결과: {predictions_and}")
print(f"실제 타겟:   {y_and}")

LAB 7-3

OR 연산 학습

학습된 OR 퍼셉트론으로 예측:
입력:
[[ 1  1]
 [ 1 -1]
 [-1  1]
 [-1 -1]]
예측 결과: [ 1  1  1 -1]
실제 타겟:   [ 1  1  1 -1]

AND 연산 학습

학습된 AND 퍼셉트론으로 예측:
입력:
[[ 1  1]
 [ 1 -1]
 [-1  1]
 [-1 -1]]
예측 결과: [ 1 -1 -1 -1]
실제 타겟:   [ 1 -1 -1 -1]


LAB 7-4

In [ ]:
import numpy as np
print("LAB 7-4\n")
# XOR 데이터셋 정의
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([0, 1, 1, 0])

def polynomial_transform(X):
    x1 = X[:, 0]
    x2 = X[:, 1]
    x1x2 = x1 * x2
    ones = np.ones(X.shape[0])

    X_poly = np.column_stack([x1, x2, x1x2, ones])
    return X_poly

# 다항 변환 적용
X_poly = polynomial_transform(X)

print("원본 입력:")
print(X)
print("\n다항 변환 후 특징 (x1, x2, x1*x2, 1):")
print(X_poly)

class Perceptron:
    def __init__(self, learning_rate=0.1, n_epochs=100):
        self.learning_rate = learning_rate
        self.n_epochs = n_epochs
        self.weights = None
        self.training_errors = []

    def activation(self, z):
        return np.where(z >= 0, 1, 0)

    def fit(self, X, y):
        n_samples, n_features = X.shape

        # 가중치 초기화
        self.weights = np.zeros(n_features)

        # 학습 반복
        for epoch in range(self.n_epochs):
            errors = 0

            for xi, target in zip(X, y):

                z = np.dot(xi, self.weights)
                prediction = self.activation(z)

                update = self.learning_rate * (target - prediction)
                self.weights += update * xi

                errors += int(update != 0.0)

            self.training_errors.append(errors)

        return self

    def predict(self, X):
        z = np.dot(X, self.weights)
        return self.activation(z)

    def score(self, X, y):
        predictions = self.predict(X)
        return np.mean(predictions == y)


perceptron = Perceptron(learning_rate=0.1, n_epochs=1000)
perceptron.fit(X_poly, y)

# 학습된 가중치 출력
print(f"\n학습된 가중치: {perceptron.weights}")
print(f"w1={perceptron.weights[0]:.2f}, w2={perceptron.weights[1]:.2f}, "
      f"w3={perceptron.weights[2]:.2f}, bias={perceptron.weights[3]:.2f}")

# 예측 결과 확인
predictions = perceptron.predict(X_poly)

print("입력 (x1, x2) | 실제값 | 예측값")
for i in range(len(X)):
    x1, x2 = X[i]
    actual = y[i]
    pred = predictions[i]
    print(f"({x1},{x2}) | {x1} XOR {x2} = {actual} | {pred}")


LAB 7-4

원본 입력:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

다항 변환 후 특징 (x1, x2, x1*x2, 1):
[[0. 0. 0. 1.]
 [0. 1. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]

학습된 가중치: [ 0.1  0.1 -0.3 -0.1]
w1=0.10, w2=0.10, w3=-0.30, bias=-0.10
입력 (x1, x2) | 실제값 | 예측값
(0,0) | 0 XOR 0 = 0 | 0
(0,1) | 0 XOR 1 = 1 | 1
(1,0) | 1 XOR 0 = 1 | 1
(1,1) | 1 XOR 1 = 0 | 0


텐서플로우를 이용한 MLP 구현

In [ ]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report
print("TensorFlow MLP\n")
# 데이터 준비
X_train = np.array([[0, 0],
                    [0, 1],
                    [1, 0],
                    [1, 1]], dtype=np.float32)

y_train = np.array([0, 1, 1, 0])

print("scikit-learn MLPClassifier를 이용한 XOR 연산")

# MLP 모델 생성
mlp = MLPClassifier(
    hidden_layer_sizes=(4, 4),
    activation='relu',
    solver='adam',
    learning_rate_init=0.1,
    max_iter=1000,
    random_state=42,
    verbose=True
)

print("\n모델 구조:")
print("입력층: 2 뉴런")
print("은닉층1: 4 뉴런 (ReLU)")
print("은닉층2: 4 뉴런 (ReLU)")
print("출력층: 1 뉴런 (Sigmoid)")

# 모델 학습
mlp.fit(X_train, y_train)

# 예측
predictions = mlp.predict(X_train)
probabilities = mlp.predict_proba(X_train)

# 평가
accuracy = accuracy_score(y_train, predictions)

print("\n예측 결과:")
print("입력 (x1, x2) | 실제값 | 예측값 | 확률값 (클래스 1)")

for i in range(len(X_train)):
    x1, x2 = X_train[i]
    actual = y_train[i]
    pred = predictions[i]
    prob = probabilities[i][1]
    print(f"({int(x1)}, {int(x2)}) | {int(actual)} | {pred} | {prob:.4f}")



TensorFlow MLP

scikit-learn MLPClassifier를 이용한 XOR 연산

모델 구조:
입력층: 2 뉴런
은닉층1: 4 뉴런 (ReLU)
은닉층2: 4 뉴런 (ReLU)
출력층: 1 뉴런 (Sigmoid)
Iteration 1, loss = 0.72561148
Iteration 2, loss = 0.70392069
Iteration 3, loss = 0.67612176
Iteration 4, loss = 0.65579365
Iteration 5, loss = 0.62459002
Iteration 6, loss = 0.59290886
Iteration 7, loss = 0.57682609
Iteration 8, loss = 0.53816946
Iteration 9, loss = 0.50723096
Iteration 10, loss = 0.46672108
Iteration 11, loss = 0.42595202
Iteration 12, loss = 0.37906117
Iteration 13, loss = 0.35478724
Iteration 14, loss = 0.32762777
Iteration 15, loss = 0.29507610
Iteration 16, loss = 0.27081287
Iteration 17, loss = 0.24701308
Iteration 18, loss = 0.21490758
Iteration 19, loss = 0.19520710
Iteration 20, loss = 0.17527288
Iteration 21, loss = 0.15650302
Iteration 22, loss = 0.13974893
Iteration 23, loss = 0.12546505
Iteration 24, loss = 0.11335049
Iteration 25, loss = 0.10292080
Iteration 26, loss = 0.09820817
Iteration 27, loss = 0.08607683
Iteration 28, lo